version: '3.1'

services:

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    db:
        image: mysql:5.6
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 7VJbsbrPMclA5Mww
            MYSQL_DATABASE: designexplorer
            MYSQL_USER: designexplorer
            MYSQL_PASSWORD: I0rEa3HJFgNtk8YH
